[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND

[program:openElevationServer]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
command=/home/demps-user/open.elevation.server/openElevationServer.py